# Due to incompatibility of newer `wasm-bindgen` versions with newer Rust versions,
# and updating to a newer version results in:
#
# ```
# ERROR signalupdates_bot: error=could not get value for key state
#
# Caused by:
#     js error: JsValue(Error: invalid type: string "fi", expected a borrowed string
#     Error: invalid type: string "fi", expected a borrowed string
#         at __wbg_Error_8c4e43fe74559d73 (shim.js:238:12)
#         ...
# ```

[toolchain]
channel = "nightly-2024-07-27"
